### ISSUE TITLE
Write support for D.a.n?

### ISSUE THREAD

**Issue by mbirth** [DacoTaco/YASDU#2]
Any chance to get write support in D.a.n? Or is there another Linux-alternative to HacDiskMount (esp. for mounting OFW Switch partitions using memload and modifying files)?

**Comment by DacoTaco** [comment]
im sadly not really in touch with the switch scene to know if there is an alternative.

i would love to give it writing support tbh,
in short all that would need to be done to add writing support is change the nand_write function ( https://github.com/DacoTaco/YASDU/blob/master/D.a.n/driver.c#L302 ) to read a block, decrypt it, write the data in the block, encrypt it again and write the encrypted block again.

at least thats the theory, i know i tried it once for a short while but never gone it to work to decrypt a certain block decently and only worked if i started decrypting from start to the block where we are writing. i never did attempt to get it to work after that xD

i should look into it though

**Comment by mbirth** [comment]
Just for the record: I've found https://github.com/ihaveamac/ninfs which seems to have write support. I'll experiment with that later this night.

**Comment by DacoTaco** [comment]
heads up : after some investigation the AES puzzle just all of a sudden fell into places in my head.
after a night of looking at the code and trying some things ive added AES encryption into D.A.N.'s crypto code which seems to encrypt all data back to their original values.

next step is to test is fully by doing some random read , decrypt, encrypt, write operations on some data.

after that it should be a piece of cake to add write support to the whole thing :)

**Comment by DacoTaco** [comment]
i just added write support to D.a.n.

however, this is untested on a switch so im really not sure if the data it writes is data the switch hardware likes.
i currently don't have emunand set up either, so if somebody that has can verify it working ... that would be great!

there is a few kinks i want to look into though to make it easier to write.
currently : 
* only root can write to the mounted nand partitions
* needs to mount without the readonly flag ( aka sudo mount -o loop /mnt/Dan/SomePartitioon /mnt/dec_Nand/SomePartition )

@mbirth : would you happen to have emunand set up?

**Comment by DacoTaco** [comment]
i just did some testing with my Emunand/emuMMC and it looks like D.A.N. has full write support now. i deleted some screenshots, copied them back and it all worked.

in the processes i changed quiet some stuff so i could test this stuff. and imo it's a lot better for practical usages.
on startup it will look for the partitions as they are knows on linux on the switch ( /dev/mmcblk1pX ). 
when using -l (local files) it will look for all knows files that are in the same folder as d.a.n. 
those are : 
- 'NAND'. this is a file that should be a full nand backup. this can also be your emunand if you want
- 'PRODINFO' and/or 'PRODINFOF' : product info partition
- 'SAFE' : safe mode partition
- 'SYSTEM' : system partition
- 'USER' : user partition containing all user data

if it found NAND, it will do all access and processing directly to the nand backup.

it is possible writing can only be done by su/root, so don't forget to add sudo if you want to write anything!
